apiVersion: v1
kind: Secret
metadata:
  name: istio-helm-repo
  namespace: argocd
  labels:
    argocd.argoproj.io/secret-type: repository
stringData:
  url: {{ .Values.istio.spec.source.url }}
  name: istio.io
  type: helm
