apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: elk-app
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: elk-system
    server: {{ .Values.k8s.spec.destination.server }}
  project: default
  source:
    chart: eck-operator-crds
    repoURL: {{ .Values.istio.spec.source.url }}
    targetRevision: HEAD
