apiVersion: v1
kind: Secret
metadata:
  name: elk-helm-repo
  namespace: argocd
  labels:
    argocd.argoproj.io/secret-type: repository
stringData:
  url: {{ .Values.elk.spec.source.url }}
  name: elastic.co
  type: helm
